import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signInWithRedirect, getRedirectResult, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, collection, addDoc, doc, updateDoc, deleteDoc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDflagsO6GHf2Lzw62DX03ZWkjVVO-JgU4',authDomain:'the-prayer-app-8cd65.firebaseapp.com',projectId:'the-prayer-app-8cd65',storageBucket:'the-prayer-app-8cd65.firebasestorage.app',messagingSenderId:'739737957390',appId:'1:739737957390:web:d5b8d0ad2d4c7064f7b85f',measurementId:'G-EETB34E7CY'};
const firebaseApp=initializeApp(firebaseConfig);const auth=getAuth(firebaseApp);const db=getFirestore(firebaseApp);const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});
const $=id=>document.getElementById(id);let user=null,names=[],selectedId=null,unsubscribe=null,toastTimer=null;

const loading=$('loading'),signedOut=$('signed-out'),appEl=$('app'),errorEl=$('sign-in-error');
function showOnly(el){[loading,signedOut,appEl].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden')}
function listRef(){return collection(db,'users',user.uid,'names')}
function formatDate(value){if(!value)return'';const date=value.toDate?value.toDate():new Date(value);return new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric'}).format(date)}
function escapeHtml(value=''){return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2400)}
function sorted(items){return [...items].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)||a.name.localeCompare(b.name))}
function card(item,showStatus=false){const detail=item.details?`<p>${escapeHtml(item.details)}</p>`:'';const pill=showStatus?`<span class="status-pill">${item.status==='celebrate'?'Celebrate':'Pray'}</span>`:'';return `<article class="name-card"><div><h3>${escapeHtml(item.name)}</h3>${detail}</div>${pill}<button type="button" data-open="${item.id}">View</button></article>`}
function render(){const prayers=sorted(names.filter(n=>n.status!=='celebrate'));const celebrations=sorted(names.filter(n=>n.status==='celebrate'));$('prayer-list').innerHTML=prayers.map(n=>card(n)).join('');$('celebrate-list').innerHTML=celebrations.map(n=>card(n)).join('');$('prayer-empty').classList.toggle('hidden',prayers.length>0);$('celebrate-empty').classList.toggle('hidden',celebrations.length>0);renderAll()}
function renderAll(){const query=$('search-input').value.trim().toLowerCase();const filtered=sorted(names).filter(n=>`${n.name} ${n.details||''}`.toLowerCase().includes(query));$('all-list').innerHTML=filtered.map(n=>card(n,true)).join('');$('all-empty').classList.toggle('hidden',filtered.length>0)}
function listen(){if(unsubscribe)unsubscribe();unsubscribe=onSnapshot(listRef(),snap=>{names=snap.docs.map(d=>({id:d.id,...d.data()}));render()},err=>{console.error(err);showToast('Could not load your list')})}

$('sign-in-button').addEventListener('click',async()=>{errorEl.textContent='';try{await signInWithPopup(auth,provider)}catch(err){if(['auth/popup-blocked','auth/cancelled-popup-request','auth/operation-not-supported-in-this-environment'].includes(err.code)){await signInWithRedirect(auth,provider)}else if(err.code!=='auth/popup-closed-by-user'){errorEl.textContent='Google sign-in did not finish. Please try again.'}}});
getRedirectResult(auth).catch(()=>{errorEl.textContent='Google sign-in did not finish. Please try again.'});
onAuthStateChanged(auth,current=>{user=current;if(!current){if(unsubscribe){unsubscribe();unsubscribe=null}names=[];showOnly(signedOut);return}$('user-name').textContent=current.displayName||'Signed in';$('user-email').textContent=current.email||'';$('avatar-fallback').textContent=(current.displayName||current.email||'P').charAt(0).toUpperCase();if(current.photoURL){$('user-avatar').src=current.photoURL;$('avatar-fallback').classList.add('hidden')}else{$('user-avatar').removeAttribute('src');$('avatar-fallback').classList.remove('hidden')}showOnly(appEl);listen()});
$('account-button').addEventListener('click',e=>{e.stopPropagation();$('account-menu').classList.toggle('hidden')});document.addEventListener('click',()=> $('account-menu').classList.add('hidden'));$('sign-out-button').addEventListener('click',()=>signOut(auth));
$('quick-add-form').addEventListener('submit',async e=>{e.preventDefault();const input=$('quick-name'),name=input.value.trim();if(!name)return;input.value='';try{await addDoc(listRef(),{name,details:'',status:'pray',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});showToast(`${name} added`);input.focus()}catch{input.value=name;showToast('Could not add that name')}});
document.querySelectorAll('.nav-button').forEach(button=>button.addEventListener('click',()=>{const view=button.dataset.view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(`${view}-view`).classList.add('active-view');document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b===button));$('page-title').textContent={pray:'Pray',all:'All names',celebrate:'Celebrate'}[view];scrollTo({top:0,behavior:'smooth'})}));
$('search-input').addEventListener('input',renderAll);document.addEventListener('click',e=>{const button=e.target.closest('[data-open]');if(button)openDetails(button.dataset.open)});
function openDetails(id){const item=names.find(n=>n.id===id);if(!item)return;selectedId=id;$('details-title').textContent=item.name;$('details-name').value=item.name;$('details-text').value=item.details||'';$('toggle-status-button').textContent=item.status==='celebrate'?'Return to Pray':'✦ Celebrate that they’re doing well';$('modal-backdrop').classList.remove('hidden');$('details-name').focus()}
function closeDetails(){$('modal-backdrop').classList.add('hidden');selectedId=null}
$('close-modal').addEventListener('click',closeDetails);$('modal-backdrop').addEventListener('click',e=>{if(e.target===$('modal-backdrop'))closeDetails()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetails()});
$('details-form').addEventListener('submit',async e=>{e.preventDefault();if(!selectedId)return;const name=$('details-name').value.trim();if(!name)return;await updateDoc(doc(db,'users',user.uid,'names',selectedId),{name,details:$('details-text').value.trim(),updatedAt:serverTimestamp()});closeDetails();showToast('Details saved')});
$('toggle-status-button').addEventListener('click',async()=>{const item=names.find(n=>n.id===selectedId);if(!item)return;const next=item.status==='celebrate'?'pray':'celebrate';await updateDoc(doc(db,'users',user.uid,'names',selectedId),{status:next,updatedAt:serverTimestamp()});closeDetails();showToast(next==='celebrate'?'PTL! Moved to Celebrate':'Returned to Pray')});
$('delete-button').addEventListener('click',async()=>{const item=names.find(n=>n.id===selectedId);if(!item||!confirm(`Remove ${item.name} completely?`))return;await deleteDoc(doc(db,'users',user.uid,'names',selectedId));closeDetails();showToast(`${item.name} removed`)});
$('share-button').addEventListener('click',async()=>{const data={title:'Prayer Companion',text:'A simple, private place to keep a prayer list.',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);showToast('Link copied')}}catch(err){if(err.name!=='AbortError')showToast('Could not share the link')}});
